(define (make-point x y)
	(cons x y))
(define (x-point p)
	(car p))
(define (y-point p)
	(cdr p))
(define (make-segment start end)
	(cons start end))
(define (start-segment l) 
	(car l))
(define (end-segment l)
	(cdr l))
(define (print-point p)
	(newline)
	(display "(")
	(display (x-point p))
	(display ",")
	(display (y-point p))
	(display ")"))
(define (midpoint-segment l)
	(make-point (/ (+ (x-point (start-segment l)) 
					  (x-point (end-segment l)))
				    2)
				(/ (+ (y-point (start-segment l))
				      (y-point (end-segment l)))
				    2)))
