(define nil '())
(define (fringe x)
	(if (= (cdr x) nil)
		(car x)
		(if (pair? (car x))
			(fringe (car x))
			(append (car x)
					(fringe (cdr x))))))
	(define (fr-iter x)
		(cond ((null? x) nil)
			  ((not (pair? x)) (list x))
			  (else (append (fr-iter (car x)) (fr-iter (cdr x))))))
(define x (list (list 1 2) (list 3 4)))
