(define (scale-tree tree factor)
	(map (lambda (sub-tree)
			(if (pair? sub-tree)
				(scale-tree sub-tree factor)
				(* sub-tree factor)))
		 tree))
(define x (list 1 (list 2 (list 3 4) 5) (list 6 7)))
